export const COOKIE_BANNER_CLASS = 'cookie-banner'
export const COOKIE_BANNER_QUESTION_CLASS = 'cookie-banner__question'
export const COOKIE_BANNER_CONFIRMATION_CLASS = 'cookie-banner__confirmation-message'
export const ACCEPT_ALL_CLASS = 'acceptAll'
export const HIDE_BUTTON_CLASS = 'cookie-banner__hide-button'