export const TRANSITIONAL_CONTAINER_ID = 'GTM-TSFTCWZ';
export const A_CONTAINER_ID = 'GTM-NDJKHWK';
export const B_CONTAINER_ID = 'GTM-P39VTVL';
export const C_CONTAINER_ID = 'GTM-MTGZWNQ';
export const D_CONTAINER_ID = 'GTM-MWXH5Z3';
export const E_CONTAINER_ID = 'GTM-56HJH7C';
export const F_CONTAINER_ID = 'GTM-MGQJ86G';
export const SDES_CONTAINER_ID = 'GTM-WT6TT3X';
